### ISSUE TITLE
Changing filters in top golden list always re-fetches whole list

### ISSUE THREAD

**Issue by whatsGravity** [yoshiyoshyosh/goldberries#14]
Fetching the top golden list is a bit slow, and changing any filters completely re-fetches the list.
This is not true of the campaign list page, where it'll (presumably) load a cached version of the filtered view if it's already been loaded. 
Imo, top list should behave the same way, since it's a bit annoying to have to wait for a whole network request round-trip every time you update the filters.
Admittedly this isn't a super common use case, so I'm only suggesting since it seems like that's how the campaign list already behaves.

Longer term, it would be cool if the site rendered a cached version of the top list and then sent a background request to fetch up to date data and update the list with it, since the ~5s delay is mildly annoying at the moment.

**Comment by viddie** [comment]
there is a reason for this: when its cached, react will render the result immediately. if you are navigating to the top golden list from a different page, it means the navigation will look "stuck" for ~2 seconds, before displaying the top golden list.

for the campaign list i fixed this by rendering the campaigns in groups, which dramatically reduced the time it takes until you can use the navigation again. i could maybe do something similar to the top golden list, to render the tiers individually with a time delay to not clog up the rest of the page, and when thats done the page can easily be cached as well
