### ISSUE TITLE
Restrict allowed characters for names

### ISSUE THREAD

**Issue by viddie** [yoshiyoshyosh/goldberries#37]

**Comment by yoshiyoshyosh** [comment]
what characters?

**Comment by viddie** [comment]
![image](https://github.com/yoshiyoshyosh/goldberries/assets/11546103/6e445990-07a5-4679-864b-af4264ab26a0)
![image](https://github.com/yoshiyoshyosh/goldberries/assets/11546103/c1f3da59-5bec-4b43-830c-5d9d309b65c9)

im not sure yet how to properly implement it, but stuff like this shouldnt be a thing. so only allow alpha numeric characters, chinese symbols, maybe emojis and other stuff im not thinking about now
