### ISSUE TITLE
Add icons for player's profile links 

### ISSUE THREAD

**Issue by RisingSunLight42** [yoshiyoshyosh/goldberries#68]
I've added several links to my profile and saw that YouTube and Twitch icons where implemented, but not other websites such as Twitter, so here's some suggestions.

- [Twitter icon](https://fontawesome.com/icons/twitter?f=brands&s=solid) or [X icon](https://fontawesome.com/icons/x-twitter?f=brands&s=solid)
- [Github icon](https://fontawesome.com/icons/github?f=brands&s=solid)
- [Instagram icon](https://fontawesome.com/icons/instagram?f=brands&s=solid)
- [Trophy icon for Speedrun.com](https://fontawesome.com/icons/trophy?s=solid)
- [Reddit icon](https://fontawesome.com/icons/reddit?f=brands&s=solid)

I stayed and focused on fontawesome icons, but if you accept icons that are png or something, I think more websites could be added (but I doubt everything would be useful even in my list lmao).

Btw, there's also a [Discord icon](https://fontawesome.com/icons/discord?f=brands&s=solid) and I think it could be a good addition to add the Discord of people who have linked their account to the website (with an opt-in/opt-out to display it or not).

**Comment by viddie** [comment]
Adding [Steam](https://fontawesome.com/icons/steam?f=brands&s=solid) into the mix
